/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import javax.imageio.ImageIO;
import javax.lang.model.SourceVersion;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.SQLOutput;
import java.util.Arrays;

public class App {

    public static void main(String[] args) throws IOException {
//        File inputFile = new File("./assets/mario.bmp");
        String outputPath = "./assets/";
        String inputPath = "./assets/mario.bmp";
//        Bitmap image = new Bitmap(inputFile, outputFile, "Change");
//        BufferedImage image = ImageIO.read(new File("./assets/mario.bmp"));
//        ImageIO.write(image, "png", outputFile);
//        Bitmap createGreyScale = new Bitmap(inputPath, outputPath, "greyScale.bmp");
//        createGreyScale.greyScale();

//        Bitmap createMirror = new Bitmap(inputPath, outputPath, "mirror.bmp");
//        createMirror.mirror();

        Bitmap yellify = new Bitmap(inputPath, outputPath, "yellify.bmp");
        yellify.yellify();



    }
}
