/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import javax.imageio.ImageIO;
import javax.lang.model.SourceVersion;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.SQLOutput;

public class App {

    public static void main(String[] args) throws IOException {
//        File inputFile = new File("./assets/mario.bmp");
//        File outputFile = new File("./assets/outputMario.bmp");
//        Bitmap image = new Bitmap(inputFile, outputFile, "Change");
//
//        System.out.println(image);
        BufferedImage image = ImageIO.read(new File("./assets/mario.bmp"));
        System.out.println("image = " + image);

    }
}
